package com.learnreanimated

enum class Delays(val value: Long) {
    AFTER_DOT_DELAY(300),
    DOT_DELAY(300),
    AFTER_DASH_DELAY(400),
    DASH_DELAY(600),
    DELAY_AFTER_LETTER(500),
    SPACE(1000),
}

enum class MorseSymbols(val symbol: String) {
    DOT("."),
    DASH("-")
}

enum class Morse(val letter: List<MorseSymbols>) {
    A(listOf(MorseSymbols.DOT, MorseSymbols.DASH)),
    B(listOf(MorseSymbols.DASH, MorseSymbols.DOT, MorseSymbols.DOT, MorseSymbols.DOT)),
    C(listOf(MorseSymbols.DASH, MorseSymbols.DOT, MorseSymbols.DASH, MorseSymbols.DOT)),
    D(listOf(MorseSymbols.DASH, MorseSymbols.DOT)),
    E(listOf(MorseSymbols.DOT)),
    F(listOf(MorseSymbols.DOT, MorseSymbols.DOT, MorseSymbols.DASH, MorseSymbols.DOT)),
    G(listOf(MorseSymbols.DASH, MorseSymbols.DASH, MorseSymbols.DOT)),
    H(listOf(MorseSymbols.DOT, MorseSymbols.DOT, MorseSymbols.DOT, MorseSymbols.DOT)),
    I(listOf(MorseSymbols.DOT, MorseSymbols.DOT)),
    J(listOf(MorseSymbols.DOT, MorseSymbols.DASH, MorseSymbols.DASH, MorseSymbols.DASH)),
    K(listOf(MorseSymbols.DASH, MorseSymbols.DOT, MorseSymbols.DASH)),
    L(listOf(MorseSymbols.DOT, MorseSymbols.DASH, MorseSymbols.DOT, MorseSymbols.DOT)),
    M(listOf(MorseSymbols.DASH, MorseSymbols.DASH)),
    N(listOf(MorseSymbols.DASH, MorseSymbols.DOT)),
    O(listOf(MorseSymbols.DASH, MorseSymbols.DASH, MorseSymbols.DASH)),
    P(listOf(MorseSymbols.DOT,  MorseSymbols.DASH,  MorseSymbols.DASH, MorseSymbols.DOT)),
    Q(listOf(MorseSymbols.DASH,  MorseSymbols.DASH,  MorseSymbols.DOT, MorseSymbols.DASH)),
    R(listOf(MorseSymbols.DOT,  MorseSymbols.DASH, MorseSymbols.DOT)),
    S(listOf(MorseSymbols.DOT,  MorseSymbols.DOT, MorseSymbols.DOT)),
    T(listOf(MorseSymbols.DASH)),
    U(listOf(MorseSymbols.DOT,  MorseSymbols.DOT,  MorseSymbols.DASH)),
    V(listOf(MorseSymbols.DOT,  MorseSymbols.DOT,  MorseSymbols.DOT, MorseSymbols.DASH)),
    W(listOf(MorseSymbols.DOT,  MorseSymbols.DASH,  MorseSymbols.DASH)),
    X(listOf(MorseSymbols.DASH,  MorseSymbols.DOT,  MorseSymbols.DOT, MorseSymbols.DASH)),
    Y(listOf(MorseSymbols.DASH,  MorseSymbols.DOT,  MorseSymbols.DASH, MorseSymbols.DASH)),
    Z(listOf(MorseSymbols.DASH,  MorseSymbols.DASH,  MorseSymbols.DOT, MorseSymbols.DOT)),
    ONE(listOf(MorseSymbols.DOT,  MorseSymbols.DASH, MorseSymbols.DASH, MorseSymbols.DASH, MorseSymbols.DASH,)),
    TWO(listOf(MorseSymbols.DOT,  MorseSymbols.DOT, MorseSymbols.DASH, MorseSymbols.DASH, MorseSymbols.DASH,)),
    THREE(listOf(MorseSymbols.DOT,  MorseSymbols.DOT, MorseSymbols.DOT, MorseSymbols.DASH, MorseSymbols.DASH,)),
    FOR(listOf(MorseSymbols.DOT,  MorseSymbols.DOT, MorseSymbols.DOT, MorseSymbols.DOT, MorseSymbols.DASH,)),
    FIVE(listOf(MorseSymbols.DOT,  MorseSymbols.DOT, MorseSymbols.DOT, MorseSymbols.DOT, MorseSymbols.DOT,)),
    SIX(listOf(MorseSymbols.DASH,  MorseSymbols.DOT, MorseSymbols.DOT, MorseSymbols.DOT, MorseSymbols.DOT,)),
    SEVEN(listOf(MorseSymbols.DASH,  MorseSymbols.DASH, MorseSymbols.DOT, MorseSymbols.DOT, MorseSymbols.DOT,)),
    EIGHT(listOf(MorseSymbols.DASH,  MorseSymbols.DASH, MorseSymbols.DASH, MorseSymbols.DOT, MorseSymbols.DOT,)),
    NINE(listOf(MorseSymbols.DASH,  MorseSymbols.DASH, MorseSymbols.DASH, MorseSymbols.DASH, MorseSymbols.DOT,)),
    ZERO(listOf(MorseSymbols.DASH,  MorseSymbols.DASH, MorseSymbols.DASH, MorseSymbols.DASH, MorseSymbols.DASH,)),
}

val morseDictionary = mapOf(
    'a' to Morse.A.letter,
    'b' to Morse.B.letter,
    'c' to Morse.C.letter,
    'd' to Morse.D.letter,
    'e' to Morse.E.letter,
    'f' to Morse.F.letter,
    'g' to Morse.G.letter,
    'h' to Morse.H.letter,
    'i' to Morse.I.letter,
    'j' to Morse.J.letter,
    'k' to Morse.K.letter,
    'l' to Morse.L.letter,
    'm' to Morse.M.letter,
    'n' to Morse.N.letter,
    'o' to Morse.O.letter,
    'p' to Morse.P.letter,
    'q' to Morse.Q.letter,
    'r' to Morse.R.letter,
    's' to Morse.S.letter,
    't' to Morse.T.letter,
    'u' to Morse.U.letter,
    'v' to Morse.V.letter,
    'w' to Morse.W.letter,
    'x' to Morse.X.letter,
    'y' to Morse.Y.letter,
    'z' to Morse.Z.letter,
    '1' to Morse.ONE.letter,
    '2' to Morse.TWO.letter,
    '3' to Morse.THREE.letter,
    '4' to Morse.FOR.letter,
    '5' to Morse.FIVE.letter,
    '6' to Morse.SIX.letter,
    '7' to Morse.SEVEN.letter,
    '8' to Morse.EIGHT.letter,
    '9' to Morse.NINE.letter,
    '0' to Morse.ZERO.letter,
)